const AUTH_TYPES = Object.freeze({
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  VERIFY_ACCOUNT: 'VERIFY_ACCOUNT',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  EMAIL_VERIFY_SUCCESS: 'EMAIL_VERIFY_SUCCESS',
  CONNECT_CORRECT_WALLET: 'CONNECT_CORRECT_WALLET',
});

export default AUTH_TYPES;
